CREATE TABLE IF NOT EXISTS good
(
	ID          INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME        VARCHAR(255)    NOT NULL,
	SHORT_DESC  TEXT            NOT NULL,
	FULL_DESC   MEDIUMTEXT      NOT NULL,
	PRICE       INT             NOT NULL,
	IS_ACTIVE   BOOL            NOT NULL,
	GOOD_CODE   VARCHAR(55)     NOT NULL,
	TIME_CREATE DATETIME        NOT NULL,
	TIME_UPDATE DATETIME        NOT NULL
);

CREATE TABLE IF NOT EXISTS tag
(
	ID   INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(55)     NOT NULL
);
CREATE TABLE IF NOT EXISTS good_tag
(
	GOOD_ID INT NOT NULL,
	TAG_ID  INT NOT NULL,
	PRIMARY KEY (GOOD_ID, TAG_ID),
	FOREIGN KEY FK_GT_GOOD (GOOD_ID)
		REFERENCES good (ID)
		ON UPDATE RESTRICT
		ON DELETE RESTRICT,
	FOREIGN KEY FK_GT_TAG (TAG_ID)
		REFERENCES tag (ID)
		ON UPDATE RESTRICT
		ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS image
(
	ID      INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	PATH    VARCHAR(255)    NOT NULL,
	HEIGHT  INT             NOT NULL,
	WIDTH   INT             NOT NULL,
	IS_MAIN BOOL            NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS good_image
(
	GOOD_ID  INT NOT NULL,
	IMAGE_ID INT NOT NULL,
	PRIMARY KEY (GOOD_ID, IMAGE_ID),
	FOREIGN KEY FK_GI_GOOD (GOOD_ID)
		REFERENCES good (ID)
		ON UPDATE RESTRICT
		ON DELETE RESTRICT,
	FOREIGN KEY FK_GI_IMAGE (IMAGE_ID)
		REFERENCES image (ID)
		ON UPDATE RESTRICT
		ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS `order`
(
	ID          INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	GOOD_ID     INT             NOT NULL,
	DATE_CREATE DATETIME        NOT NULL,
	C_NAME      VARCHAR(255)    NOT NULL,
	C_PHONE     VARCHAR(12)     NOT NULL,
	C_EMAIL     VARCHAR(255)    NOT NULL,
	C_WISH      TEXT            NOT NULL,
	STATUS      VARCHAR(255)    NOT NULL,
	ADDRESS     VARCHAR(255)    NOT NULL,
	PRICE       INT             NOT NULL,
	FOREIGN KEY FK_ORDER_GOOD (GOOD_ID)
		REFERENCES good (ID)
		ON UPDATE RESTRICT
		ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS user
(
	ID       INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	LOGIN    VARCHAR(100)    NOT NULL,
	EMAIL    VARCHAR(255)    NOT NULL,
	PASSWORD VARCHAR(255)    NOT NULL,
	ROLE     VARCHAR(100)    NOT NULL
);